### ISSUE TITLE
Failed to link to module 'rlm_couchbase'

### ISSUE THREAD

**Issue by omar-haris** [aaronhurt/rlm_couchbase#1]
I have this error when I run freeradius -X

/etc/freeradius/mods-enabled/couchbase[1]: Failed to link to module 'rlm_couchbase': /usr/lib/freeradius/rlm_couchbase.so: cannot open shared object file: No such file or directory

**Comment by aaronhurt** [comment]
Please check the README ... this project is no longer maintained here.  This code was merged into the official FreeRADIUS project nearly 2 years ago.

[master branch](https://github.com/FreeRADIUS/freeradius-server/tree/master/src/modules/rlm_couchbase)
[v3.1.x branch](https://github.com/FreeRADIUS/freeradius-server/tree/v3.1.x/src/modules/rlm_couchbase)
[v3.0.x branch](https://github.com/FreeRADIUS/freeradius-server/tree/v3.0.x/src/modules/rlm_couchbase)

You can build this module by simply enabling it when you build the server and other components.

**Comment by omar-haris** [comment]
Thanks for you reply ,
how  to enabling the module do you have an example ?

**Comment by aaronhurt** [comment]
Look at the README in the links I pasted.

https://github.com/FreeRADIUS/freeradius-server/tree/v3.0.x/src/modules/rlm_couchbase#to-use

Then you just build the server as you would normally. 

https://github.com/FreeRADIUS/freeradius-server/blob/v3.0.x/INSTALL.rst

**Comment by omar-haris** [comment]
@leprechau  thanks
